### ISSUE TITLE
Figure out the right implementation of thread_local memory

### ISSUE THREAD

**Issue by loganek** [WebAssembly/wasi-threads#3]
I think there are 2 feasible options to implement it:
* use WASM globals - since the proposal (at least for now) is to clone the whole module, that means that all the globals are copied as well, so that will already provide thread local memory
* have a reserved slot in linear memory for each thread

I don't know yet which approach is better (also what `better` actually means) but I think we need to explore those two paths (unless anybody already knows that one or the other won't work). Also, if there are other options on the table, let's consider them as well.

**Comment by AlexEne** [comment]
@sbc100 What does emscriptem do for thread locals today in browsers?

**Comment by sbc100** [comment]
Thread local memory needs to be part of linear memory since its just memory from C ABI pointer of view.   Once you have a TLS address you can pass it around like any other.  For example, all function that operate on liner memory need to work for TLS address as well as non-TLS addresses (e.g. memcpy). 

We can and do use wasm globals for some things, such as to store the stack pointer and the tls base pointer.   The way clang/llvm/wasm-ld do this today is that TLS address are accessed as offsets from a `__tls_base` wasm global, similar to how stack addresses are offset from the `__stack_base` global.    Here is an example of the codegen for accessing a TLS global: https://github.com/llvm/llvm-project/blob/59179d72b2e3d3b99ebc342374c9c797d526ac5d/llvm/test/CodeGen/WebAssembly/tls-local-exec.ll#L8-L17

As well as `__stack_base` and `__tls_base` (which are writable globals) the linker will also synthesize two read-only wasm globals called `__tls_size` and `__tls_align` which the runtime (for example wasi-libc's startup code for threads) can use to allocate the TLS memory for each thread.

To linker synthetic symbols are mentioned here in the wasm-ld source:  https://github.com/llvm/llvm-project/blob/59179d72b2e3d3b99ebc342374c9c797d526ac5d/lld/wasm/Symbols.h#L519-L535

The runtime support code in emscirpten that consumes these values and sets `__tls_base` accordingly is here: https://github.com/emscripten-core/emscripten/blob/fafcc8649be58dacd13588dc0115eebb9f0baa1b/system/lib/pthread/emscripten_tls_init.c#L59-L77.  Note that the wasi-libc version of this code can be much simpler since there is no dynamic linking (so only one TLS region in each program).

**Comment by 12101111** [comment]
I have a implement of TLS for wasi-libc: https://github.com/12101111/wasi-libc/tree/threads-tls

A notable change is `__wasilibc_pthread_self` is not a `global`, but a thread local struct. `start_args->thread` is replaced by `tls_base`, and `wasi_thread_start` will set `__tls_base` to this value. After that `struct pthread` can be accessed using `pthread_self`. So we don't need another `global`, and pthread api that using `pthread_self` will works on main thread.

**Comment by abrown** [comment]
Cool, I was just thinking about this (the "copy the TLS" part). Do you feel good about open a PR (even draft) of [your commit](https://github.com/12101111/wasi-libc/commit/7befbaf709780e19d56b5a045960c511bd00cd92)?

**Comment by sbc100** [comment]
Nice work!   Interesting to make `pthread_self` part of TLS rather than the other way around.    I guess it means pthread_self is `global.get + i32.const` rather than just `global.get` but that doesn't seem like much of a difference.

**Comment by loganek** [comment]
Feels like the issue can be resolved now. TLS in wasi-libc was implemented already using globals (`__tls_base`) which points to a region in linear memory. I'm resolving the issue now.
